24 list2
michael-greene-ey/sr-dev-project pull request #5
Opened 2023-06-07 16:02 UTC by michael-greene-ey

Commit comments may be confusing. Was my attempt to clean everything up and work on one branch.

2023-06-07 19:27 UTC, dmathisen commented on src/components/CardHome.tsx
> +        style={{ width: "1000px", height: "800px" }}
Is it intentional to have a fixed width and height?
I'm not sure what screens your targeting, but this means there's going to be horizontal scroll bars on tablets or even laptops with low resolution.

A more common pattern is something like `width: 90%; max-width: 1100px;` so you're saying "make it 90% of the screen, but don't go above a certain width (as sites tend to look bad when stretched too wide). Or maybe `width: 100%; margin: 0 15px; max-width: 1100px;`.

It's fine if it's intentionally like this, but wanted to make sure.

2023-06-07 19:30 UTC, dmathisen commented on src/components/CardPage.module.css
> +  size: 10px !important;
Why is important needed? Can you remove `!important` by making the selector more specific? `.cardContainer .title { size: 10px; }`

I'm not sure why it's needed above. But in general, if you use `!important` on a class name (even worse with a common class name like `.title`), you'll find you have to use `!important` every time you need to change it anywhere and end up in an `!important` hell.

2023-06-07 19:32 UTC, dmathisen commented on src/components/CardHome.tsx
> -        className="bg-dark text-white"
Good changes here 👍

2023-06-07 20:21 UTC, ninohero requested changes
a few comments to the new code

2023-06-07 20:21 UTC, ninohero commented on src/components/CardHome.module.css
> +  padding-bottom: 1%;
I'm not sure it is considered good practice to use percentages for margin and padding.  px or rem/em is usually better, especially for something like a card

2023-06-07 20:21 UTC, ninohero commented on src/components/Footer.module.css
> +  padding: 3% 11% 0 11%;
again, padding being measured in percentage seems odd.  

In other details you don't need the second 11% (padding: 3% 11% 0; means the same thing)

2023-06-07 20:21 UTC, ninohero commented on src/components/Footer.module.css
> +  padding: 1em 5.5em;
I feel like you should be more consistent with units on absolute sizes.  ie: either px or rem or em.

2023-06-07 20:21 UTC, ninohero commented on src/components/Navbar.module.css
> +  margin-right: 2.5em;
on line 5 you size margin in px and here in em.  you should pick one

2023-06-07 20:21 UTC, ninohero commented on src/components/SingleCarousel.tsx
> +            <>
this containing <></> isn't necessary since there's only a single element in the return

2023-06-07 20:21 UTC, ninohero commented on src/pages/HealthContent.module.css
> +  padding-bottom: 1%;
padding in percentage is weird

2023-06-08 19:11 UTC, michael-greene-ey commented on src/components/CardPage.module.css
> +  size: 10px !important;
I was using it as a debugging tool and forgot to take it off

2023-06-09 17:30 UTC, dmathisen commented on src/components/CardHome.tsx
> +        style={{ width: "1000px", height: "800px" }}
What device(s) is the app supposed to be used for? There's so many hardcoded widths and heights. It's going to be a horrible experience if trying to access this site on a tablet or mobile. Is that okay?

2023-06-09 19:38 UTC, ninohero approved these changes
lgtm!  responsiveness is going to be done in another ticket

2023-06-09 20:39 UTC, merged